<a href="https://colab.research.google.com/github/hanjeongseop/Data/blob/main/4_1_%EC%A0%81%EC%A0%95_%EB%AA%A8%EB%8D%B8_%EC%B0%BE%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 알고리즘 별 성능 비교를 통한 적정 모델 찾기

### 1 Scaling : 숫자데이터의 서로 다른 차원(scale)을 맞춰주는 작업

In [ ]:
import pandas as pd

In [ ]:
# 파일 읽기 및 내용 확인하기

github_csv_url = 'https://raw.githubusercontent.com/hanjeongseop/Data/main'

df1 = pd.read_csv(github_csv_url + '/Contract.csv')

df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51301 entries, 0 to 51300
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          51301 non-null  int64
 1   Member_ID      51301 non-null  int64
 2   Sales_Type     51301 non-null  object
 3   Contract_Type  51301 non-null  object
 4   Channel        51301 non-null  object
 5   Datetime       51301 non-null  object
 6   Term           51301 non-null  int64
 7   Payment_Type   51301 non-null  object
 8   Product_Type   51301 non-null  object
 9   Amount_Month   51301 non-null  int64
 10  Customer_Type  51299 non-null  object
 11  Age            44329 non-null  float64
 12  Address1       51299 non-null  object
 13  Address2       51299 non-null  object
 14  State          51301 non-null  object
 15  Overdue_count  51301 non-null  int64
 16  Overdue_Type   51301 non-null  object
 17  Gender         51301 non-null  object
 18  Credit_Rank    42520 non-null  float64
 19  Bank           48542 non-null  object
dtypes: float64(2), int64(5), object(13)
memory usage: 7.8+ MB

In [ ]:
# 신용등급, 연체건수, 나이, 계약금액, 계약개월
df2 = df1[['Credit_Rank', 'Overdue_count', 'Age', 'Amount_Month', 'Term']]

In [ ]:
df2.describe()

        Credit_Rank  Overdue_count           Age   Amount_Month          Term
count  42520.000000   51301.000000  44329.000000   51301.000000  51301.000000
mean       3.428810       0.161381     50.024093   93994.974289     55.639149
std        2.213453       1.122193     10.983877   15304.263988     12.009915
min        0.000000       0.000000     25.000000   54603.000000     12.000000
25%        1.000000       0.000000     42.000000   81900.000000     60.000000
50%        3.000000       0.000000     49.000000   96900.000000     60.000000
75%        5.000000       0.000000     57.000000   98400.000000     60.000000
max       10.000000      15.000000    102.000000  215700.000000     60.000000

In [ ]:
# 변수 마다 독립적인 스케일을 가지고 있다.
# 따라서 스케일올 맞춰줘야 한다.

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler

In [ ]:
# 각각의 데이터를 확인해 스케일을 변환

scaler = StandardScaler()
scaler.fit(df2)

StandardScaler()

In [ ]:
pd.DataFrame(scaler.transform(df2)).describe()

                  0             1             2             3             4
count  4.252000e+04  5.130100e+04  4.432900e+04  5.130100e+04  5.130100e+04
mean   2.105559e-17 -1.558177e-17 -4.680423e-17  3.440456e-16 -1.883663e-17
std    1.000012e+00  1.000010e+00  1.000011e+00  1.000010e+00  1.000010e+00
min   -1.549096e+00 -1.438099e-01 -2.278282e+00 -2.573947e+00 -3.633629e+00
25%   -1.097307e+00 -1.438099e-01 -7.305420e-01 -7.903086e-01  3.631078e-01
50%   -1.937312e-01 -1.438099e-01 -9.323703e-02  1.898199e-01  3.631078e-01
75%    7.098450e-01 -1.438099e-01  6.351114e-01  2.878328e-01  3.631078e-01
max    2.968785e+00  1.322301e+01  4.732072e+00  7.952438e+00  3.631078e-01

# 평균이 0으로 표준편차는 1을 기준으로 변환되었다.

# 실제 실무에서는 이상치가 존재할 수 있기때문에 RobustScaler을 많이 사용한다.

In [ ]:
scaler = RobustScaler()
scaler.fit(df2)

RobustScaler()

In [ ]:
pd.DataFrame(scaler.transform(df2)).describe()

                  0             1             2             3             4
count  42520.000000  51301.000000  44329.000000  51301.000000  51301.000000
mean       0.107202      0.161381      0.068273     -0.176062     -4.360851
std        0.553363      1.122193      0.732258      0.927531     12.009915
min       -0.750000      0.000000     -1.600000     -2.563455    -48.000000
25%       -0.500000      0.000000     -0.466667     -0.909091      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.500000      0.000000      0.533333      0.090909      0.000000
max        1.750000     15.000000      3.533333      7.200000      0.000000

# 특정값이 많이 존재하는 경우에는 0으로 나타날 수 있다.
# 사전에 데이터 정제 작업을 통해 해결할 수 있다.

In [ ]:
# MinMaxScalersms 분류모델을 이용하는 경우 사용한다.

scaler = MinMaxScaler()
scaler.fit(df2)

MinMaxScaler()

In [ ]:
pd.DataFrame(scaler.transform(df2)).describe()

                  0             1             2             3             4
count  42520.000000  51301.000000  44329.000000  51301.000000  51301.000000
mean       0.342881      0.010759      0.324988      0.244523      0.909149
std        0.221345      0.074813      0.142648      0.095000      0.250207
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.100000      0.000000      0.220779      0.169444      1.000000
50%        0.300000      0.000000      0.311688      0.262556      1.000000
75%        0.500000      0.000000      0.415584      0.271867      1.000000
max        1.000000      1.000000      1.000000      1.000000      1.000000

### 2 Encoding : 문자데이터를 숫자데이터로 변환

In [ ]:
# 문자열 데이터 탐색

df1.head()

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,Customer_Type,Age,Address1,Address2,State,Overdue_count,Overdue_Type,Gender,Credit_Rank,Bank
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,개인,42.0,경기도,경기도,계약확정,0,없음,여자,9.0,새마을금고
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,2.0,현대카드
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,개인,48.0,경기도,경기도,계약확정,0,없음,여자,8.0,우리은행
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,개인,39.0,경기도,경기도,계약확정,0,없음,남자,5.0,농협회원조합
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,개인,60.0,경기도,경기도,기간만료,12,있음,남자,8.0,농협회원조합

In [ ]:
df1['Address1']

0          경기도
1          경기도
2          경기도
3          경기도
4          경기도
         ...
51296      경기도
51297      경기도
51298    서울특별시
51299    서울특별시
51300    서울특별시
Name: Address1, Length: 51301, dtype: object

In [ ]:
df1['Address1'].value_counts()

Address1
경기도      18353
경상도      12657
서울특별시     9038
충청도       4871
전라도       4698
강원도       1244
제주도        437
광주광역시        1
Name: count, dtype: int64

In [ ]:
# 라벨인코딩 적용

from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder = LabelEncoder()
encoder.fit(df1['Address1'])

LabelEncoder()

In [ ]:
encoder.fit_transform(df1['Address1'])

array([1, 1, 1, ..., 4, 4, 4])

In [ ]:
pd.Series(encoder.fit_transform(df1['Address1'])).value_counts()

1    18353
2    12657
4     9038
7     4871
5     4698
0     1244
6      437
8        2
3        1
Name: count, dtype: int64

# 라벨인코딩을 적용한 경우 서열화가 적용될 수 있음

In [ ]:
# One Hot 인코딩 적용
# 문자열이나 범주형 데이터를 자동으로 변환한다

pd.get_dummies(df1[['Address1']])

,Address1_강원도,Address1_경기도,Address1_경상도,Address1_광주광역시,Address1_서울특별시,Address1_전라도,Address1_제주도,Address1_충청도
0,False,True,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False
3,False,True,False,False,False,False,False,False
4,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
51296,False,True,False,False,False,False,False,False
51297,False,True,False,False,False,False,False,False
51298,False,False,False,False,True,False,False,False
51299,False,False,False,False,True,False,False,False
51300,False,False,False,False,True,False,False,False

In [ ]:
df_col = pd.get_dummies(df1[['Address1']])

df3 = df1.join(df_col)

In [ ]:
# 계약과 연관된 주요인자 확인 (판매방식, 계약기간, 대여료, 나이, 미납횟수, 신용등급, 계약상태)

df1[['Sales_Type','Term','Amount_Month','Age','Overdue_count','Credit_Rank', 'State']]

      Sales_Type  Term  Amount_Month   Age  Overdue_count  Credit_Rank State
0             렌탈    60         96900  42.0              0          9.0  계약확정
1             렌탈    60        102900  39.0              0          2.0  계약확정
2             렌탈    60         96900  48.0              0          8.0  계약확정
3            멤버십    12         66900  39.0              0          5.0  계약확정
4            멤버십    12         66900  60.0             12          8.0  기간만료
...          ...   ...           ...   ...            ...          ...   ...
51296         렌탈    60         96900  47.0              0          NaN  계약확정
51297         렌탈    60         96900  42.0              0          8.0  계약확정
51298         렌탈    39        120900  65.0              0          1.0  계약확정
51299         렌탈    60         96900  54.0              0          2.0  계약확정
51300         렌탈    60         96900  53.0              0          8.0  계약확정

[51301 rows x 7 columns]

In [ ]:
df3.head()

,Index,Member_ID,Sales_Type,Contract_Type,Channel,Datetime,Term,Payment_Type,Product_Type,Amount_Month,...,Credit_Rank,Bank,Address1_강원도,Address1_경기도,Address1_경상도,Address1_광주광역시,Address1_서울특별시,Address1_전라도,Address1_제주도,Address1_충청도
0,1,66758234,렌탈,일반계약,영업방판,2019-05-06,60,CMS,DES-1,96900,...,9.0,새마을금고,False,True,False,False,False,False,False,False
1,2,66755948,렌탈,교체계약,영업방판,2020-02-20,60,카드이체,DES-1,102900,...,2.0,현대카드,False,True,False,False,False,False,False,False
2,3,66756657,렌탈,일반계약,홈쇼핑/방송,2019-02-28,60,CMS,DES-1,96900,...,8.0,우리은행,False,True,False,False,False,False,False,False
3,4,66423450,멤버십,멤버십3유형,재계약,2019-05-13,12,CMS,DES-1,66900,...,5.0,농협회원조합,False,True,False,False,False,False,False,False
4,5,66423204,멤버십,멤버십3유형,재계약,2019-05-10,12,CMS,DES-1,66900,...,8.0,농협회원조합,False,True,False,False,False,False,False,False

In [ ]:
df2 = df1[['Sales_Type','Term','Amount_Month','Age','Overdue_count','Credit_Rank', 'State']]

df2['State'].value_counts()

State
계약확정     50620
해약확정       622
기간만료        45
해약진행중       14
Name: count, dtype: int64

In [ ]:
df2['target'] = df2['State'].replace({'계약확정':0, '기간만료':0, '해약확정':1,'해약진행중':1})

/tmp/ipykernel_691/2856542389.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['target'] = df2['State'].replace({'계약확정':0, '기간만료':0, '해약확정':1,'해약진행중':1})
/tmp/ipykernel_691/2856542389.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['target'] = df2['State'].replace({'계약확정':0, '기간만료':0, '해약확정':1,'해약진행중':1})

In [ ]:
df2['target'].value_counts()

target
0    50665
1      636
Name: count, dtype: int64

In [ ]:
df3 = df2.dropna()

df3

,Sales_Type,Term,Amount_Month,Age,Overdue_count,Credit_Rank,State,target
0,렌탈,60,96900,42.0,0,9.0,계약확정,0
1,렌탈,60,102900,39.0,0,2.0,계약확정,0
2,렌탈,60,96900,48.0,0,8.0,계약확정,0
3,멤버십,12,66900,39.0,0,5.0,계약확정,0
4,멤버십,12,66900,60.0,12,8.0,기간만료,0
...,...,...,...,...,...,...,...,...
51295,렌탈,60,96900,45.0,0,1.0,계약확정,0
51297,렌탈,60,96900,42.0,0,8.0,계약확정,0
51298,렌탈,39,120900,65.0,0,1.0,계약확정,0
51299,렌탈,60,96900,54.0,0,2.0,계약확정,0
51300,렌탈,60,96900,53.0,0,8.0,계약확정,0

In [ ]:
Y = df3['target']
X = df3.drop(columns=['State','target'])

In [ ]:
pd.get_dummies(X)

,Term,Amount_Month,Age,Overdue_count,Credit_Rank,Sales_Type_렌탈,Sales_Type_멤버십
0,60,96900,42.0,0,9.0,True,False
1,60,102900,39.0,0,2.0,True,False
2,60,96900,48.0,0,8.0,True,False
3,12,66900,39.0,0,5.0,False,True
4,12,66900,60.0,12,8.0,False,True
...,...,...,...,...,...,...,...
51295,60,96900,45.0,0,1.0,True,False
51297,60,96900,42.0,0,8.0,True,False
51298,39,120900,65.0,0,1.0,True,False
51299,60,96900,54.0,0,2.0,True,False
51300,60,96900,53.0,0,8.0,True,False

In [ ]:
X1 = pd.get_dummies(X)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X1, Y, test_size=0.3)

In [ ]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

In [ ]:
# 분류모델에서 모든 평가 지표를 확인할 수 있다.
from sklearn.metrics import classification_report

print(classification_report(y_train, y_train_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99     28099
           1       1.00      0.13      0.23       354

    accuracy                           0.99     28453
   macro avg       0.99      0.56      0.61     28453
weighted avg       0.99      0.99      0.99     28453

In [ ]:
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99     12039
           1       0.09      0.02      0.03       156

    accuracy                           0.99     12195
   macro avg       0.54      0.51      0.51     12195
weighted avg       0.98      0.99      0.98     12195

## 정밀도(Precision)
 * 예측을 '참'으로 한 대상 중에 예측과 실제 값이 '참'으로 일치한 데이터의 비율

## 재현율(Recall) or 민감
 * 실제 값이 '참'인 대상 중에 예측과 실제 값이 '참'으로 일치한 데이터의 비율
  
## F1 스코어 = 정밀도와 재현율의 조화평균
 * 정밀도와 재현율이 어느 한쪽으로 치우치지 않을 때 상대적으로 높은 값을 가진다